name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/checkout@v4
    - name: Install just
      uses: extractions/setup-just@v2
    - run: just package-check

  fedora:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    container:
      image: quay.io/fedora/fedora:41
      options: "--privileged --pid=host -v /var/tmp:/var/tmp --tmpfs /tmp:rw,exec,nosuid,nodev -v /:/run/host"

    steps:
    - run: dnf -y install cargo clippy composefs-devel e2fsprogs just rustfmt
    - name: Enable fs-verity on /
      run: tune2fs -O verity $(findmnt -vno SOURCE /run/host)
    - uses: actions/checkout@v4
    - name: Run CI checks
      run: just ci
      env:
        CFS_TEST_TMPDIR: /run/host/var/tmp
